services:
  db:
    container_name: database_container
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crypto
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8.10
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"